# Generated by Django 5.2.9 on 2026-01-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['customer'], 'verbose_name': 'Корзина клиента', 'verbose_name_plural': 'Корзины клиентов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['customer', 'order_type', 'address', 'total_price', 'status'], 'verbose_name': 'Заказ клиента', 'verbose_name_plural': 'Заказы клиентов'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
